[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "runet_pkg"
version = "1.0.0"
description = "Professional C-integrated Python client"
